/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    'Home.layout': typeof import('./src/components/layouts/home.layout.vue')['default']
    'Home.page': typeof import('./src/components/pages/home.page.vue')['default']
    'Invitation.page': typeof import('./src/components/pages/invitation.page.vue')['default']
    'Login.component': typeof import('./src/components/utils/login.component.vue')['default']
    'Login.page': typeof import('./src/components/pages/login.page.vue')['default']
    'NoData.component': typeof import('./src/components/utils/noData.component.vue')['default']
    'Project_header.component': typeof import('./src/components/utils/project_utils/project_header.component.vue')['default']
    'Project_table.component': typeof import('./src/components/utils/project_utils/project_table.component.vue')['default']
    'Project.page': typeof import('./src/components/pages/project.page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Team.page': typeof import('./src/components/pages/team.page.vue')['default']
    'Ticket.page': typeof import('./src/components/pages/ticket.page.vue')['default']
    'UserProfile.page': typeof import('./src/components/pages/userProfile.page.vue')['default']
  }
}
