version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: BugTrackerDb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "" # Set an empty password (recommended for this approach)
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: BugTracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
